//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthentitification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konzola
    {
        public int idKonzole { get; set; }
        public string model { get; set; }
    }
}
