//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthentitification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int idRent { get; set; }
        public string modelKonzole { get; set; }
        public string nazivIgrice { get; set; }
        public System.DateTime datumod { get; set; }
        public System.DateTime datumdo { get; set; }
        public int cena { get; set; }
    }
}
